# Generated by Django 5.0.4 on 2024-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
