# Generated by Django 4.2.1 on 2023-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
