# Generated by Django 5.0.4 on 2024-05-18 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_movie_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
    ]
