# Generated by Django 5.0.4 on 2024-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_remove_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
