/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_expway_util_Path */

#ifndef _Included_com_expway_util_Path
#define _Included_com_expway_util_Path
#ifdef __cplusplus
extern "C" {
#endif
#undef com_expway_util_Path_serialVersionUID
#define com_expway_util_Path_serialVersionUID -2767605614048989439LL
#undef com_expway_util_Path_serialVersionUID
#define com_expway_util_Path_serialVersionUID 1224463164541339165LL
#undef com_expway_util_Path_TEXTUAL_NAVIGATION_PATH
#define com_expway_util_Path_TEXTUAL_NAVIGATION_PATH 1L
#undef com_expway_util_Path_SIEMENS_NAVIGATION_PATH
#define com_expway_util_Path_SIEMENS_NAVIGATION_PATH 2L
#undef com_expway_util_Path_ABSOLUTE_ROOT_PATH_MODE
#define com_expway_util_Path_ABSOLUTE_ROOT_PATH_MODE 1L
#undef com_expway_util_Path_ABSOLUTE_TOP_PATH_MODE
#define com_expway_util_Path_ABSOLUTE_TOP_PATH_MODE 2L
#undef com_expway_util_Path_RELATIVE_PATH_MODE
#define com_expway_util_Path_RELATIVE_PATH_MODE 3L
/*
 * Class:     com_expway_util_Path
 * Method:    decode_path
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BB)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_expway_util_Path_decode_1path
  (JNIEnv *, jobject, jstring, jstring, jbyteArray, jbyte);

/*
 * Class:     com_expway_util_Path
 * Method:    encode_path
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_expway_util_Path_encode_1path
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jbyte);

#ifdef __cplusplus
}
#endif
#endif
